/**
 * generated by Xtext 2.13.0
 */
package ac.soton.xtheory.scoping;

import ac.soton.xtheory.scoping.AbstractTheoryScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TheoryScopeProvider extends AbstractTheoryScopeProvider {
}
