/*
 * generated by Xtext 2.14.0
 */
package ac.soton.theory.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTheoryScopeProvider extends DelegatingScopeProvider {
}
