/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xtheory;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TheoryStandaloneSetup /* implements TheoryStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type TheoryStandaloneSetup");
  }
}
