/**
 * generated by Xtext 2.14.0
 */
package ac.soton.theory.xtext.theory;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Theory</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.theory.xtext.theory.Theory#getName <em>Name</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Theory#getParameters <em>Parameters</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Theory#getImports <em>Imports</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Theory#getTypes <em>Types</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Theory#getOperators <em>Operators</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Theory#getAxioms <em>Axioms</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Theory#getVariables <em>Variables</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Theory#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory()
 * @model
 * @generated
 */
public interface Theory extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.Theory#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.theory.xtext.theory.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Imports</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imports</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' attribute list.
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory_Imports()
   * @model unique="false"
   * @generated
   */
  EList<String> getImports();

  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.theory.xtext.theory.Type}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory_Types()
   * @model containment="true"
   * @generated
   */
  EList<Type> getTypes();

  /**
   * Returns the value of the '<em><b>Operators</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.theory.xtext.theory.Operator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operators</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operators</em>' containment reference list.
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory_Operators()
   * @model containment="true"
   * @generated
   */
  EList<Operator> getOperators();

  /**
   * Returns the value of the '<em><b>Axioms</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.theory.xtext.theory.Axiom}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Axioms</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Axioms</em>' containment reference list.
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory_Axioms()
   * @model containment="true"
   * @generated
   */
  EList<Axiom> getAxioms();

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.theory.xtext.theory.Variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVariables();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.theory.xtext.theory.Rule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getTheory_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // Theory
