/**
 * generated by Xtext 2.13.0
 */
package ac.soton.xtheory.ui.contentassist;

import ac.soton.xtheory.ui.contentassist.AbstractTheoryProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TheoryProposalProvider extends AbstractTheoryProposalProvider {
}
