/**
 * generated by Xtext 2.14.0
 */
package ac.soton.theory.xtext;

import ac.soton.theory.xtext.AbstractTheoryRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TheoryRuntimeModule extends AbstractTheoryRuntimeModule {
}
