/**
 * generated by Xtext 2.13.0
 */
package ac.soton.xtheory.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class TheoryQuickfixProvider extends DefaultQuickfixProvider {
}
