/*
 * generated by Xtext 2.14.0
 */
package ac.soton.theory.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTheoryValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ac.soton.theory.xtext.theory.TheoryPackage.eINSTANCE);
		return result;
	}
}
