/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xtheory.ide;

import ac.soton.xtheory.TheoryRuntimeModule;
import ac.soton.xtheory.TheoryStandaloneSetup;
import ac.soton.xtheory.ide.TheoryIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TheoryIdeSetup extends TheoryStandaloneSetup {
  @Override
  public Injector createInjector() {
    TheoryRuntimeModule _theoryRuntimeModule = new TheoryRuntimeModule();
    TheoryIdeModule _theoryIdeModule = new TheoryIdeModule();
    return Guice.createInjector(Modules2.mixin(_theoryRuntimeModule, _theoryIdeModule));
  }
}
