/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xtheory.ui;

import ac.soton.xtheory.ui.internal.XtheoryActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TheoryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(XtheoryActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		XtheoryActivator activator = XtheoryActivator.getInstance();
		return activator != null ? activator.getInjector(XtheoryActivator.AC_SOTON_XTHEORY_THEORY) : null;
	}

}
