/**
 * generated by Xtext 2.14.0
 */
package ac.soton.theory.xtext.theory;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Axiom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.theory.xtext.theory.Axiom#getComments <em>Comments</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Axiom#getName <em>Name</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Axiom#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Axiom#isIsTheorem <em>Is Theorem</em>}</li>
 * </ul>
 *
 * @see ac.soton.theory.xtext.theory.TheoryPackage#getAxiom()
 * @model
 * @generated
 */
public interface Axiom extends EObject
{
  /**
   * Returns the value of the '<em><b>Comments</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comments</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comments</em>' attribute.
   * @see #setComments(String)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getAxiom_Comments()
   * @model
   * @generated
   */
  String getComments();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.Axiom#getComments <em>Comments</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comments</em>' attribute.
   * @see #getComments()
   * @generated
   */
  void setComments(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getAxiom_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.Axiom#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Predicate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Predicate</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' attribute.
   * @see #setPredicate(String)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getAxiom_Predicate()
   * @model
   * @generated
   */
  String getPredicate();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.Axiom#getPredicate <em>Predicate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' attribute.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(String value);

  /**
   * Returns the value of the '<em><b>Is Theorem</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Theorem</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Theorem</em>' attribute.
   * @see #setIsTheorem(boolean)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getAxiom_IsTheorem()
   * @model
   * @generated
   */
  boolean isIsTheorem();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.Axiom#isIsTheorem <em>Is Theorem</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Theorem</em>' attribute.
   * @see #isIsTheorem()
   * @generated
   */
  void setIsTheorem(boolean value);

} // Axiom
