/**
 * generated by Xtext 2.14.0
 */
package ac.soton.theory.xtext.theory;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional Rewrite Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.theory.xtext.theory.ConditionalRewriteRule#getLsh <em>Lsh</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.ConditionalRewriteRule#getRhs <em>Rhs</em>}</li>
 * </ul>
 *
 * @see ac.soton.theory.xtext.theory.TheoryPackage#getConditionalRewriteRule()
 * @model
 * @generated
 */
public interface ConditionalRewriteRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Lsh</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lsh</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lsh</em>' attribute.
   * @see #setLsh(String)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getConditionalRewriteRule_Lsh()
   * @model
   * @generated
   */
  String getLsh();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.ConditionalRewriteRule#getLsh <em>Lsh</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lsh</em>' attribute.
   * @see #getLsh()
   * @generated
   */
  void setLsh(String value);

  /**
   * Returns the value of the '<em><b>Rhs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rhs</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rhs</em>' attribute.
   * @see #setRhs(String)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getConditionalRewriteRule_Rhs()
   * @model
   * @generated
   */
  String getRhs();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.ConditionalRewriteRule#getRhs <em>Rhs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rhs</em>' attribute.
   * @see #getRhs()
   * @generated
   */
  void setRhs(String value);

} // ConditionalRewriteRule
