/**
 * generated by Xtext 2.14.0
 */
package ac.soton.theory.xtext.theory;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constructor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.theory.xtext.theory.Constructor#getComments <em>Comments</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Constructor#getName <em>Name</em>}</li>
 *   <li>{@link ac.soton.theory.xtext.theory.Constructor#getDestructors <em>Destructors</em>}</li>
 * </ul>
 *
 * @see ac.soton.theory.xtext.theory.TheoryPackage#getConstructor()
 * @model
 * @generated
 */
public interface Constructor extends EObject
{
  /**
   * Returns the value of the '<em><b>Comments</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comments</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comments</em>' attribute.
   * @see #setComments(String)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getConstructor_Comments()
   * @model
   * @generated
   */
  String getComments();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.Constructor#getComments <em>Comments</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comments</em>' attribute.
   * @see #getComments()
   * @generated
   */
  void setComments(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getConstructor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ac.soton.theory.xtext.theory.Constructor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Destructors</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.theory.xtext.theory.Destructor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Destructors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destructors</em>' containment reference list.
   * @see ac.soton.theory.xtext.theory.TheoryPackage#getConstructor_Destructors()
   * @model containment="true"
   * @generated
   */
  EList<Destructor> getDestructors();

} // Constructor
