/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xtheory.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TheoryUiModule extends AbstractTheoryUiModule {
}
