/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xtheory.ide

import ac.soton.xtheory.TheoryRuntimeModule
import ac.soton.xtheory.TheoryStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TheoryIdeSetup extends TheoryStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TheoryRuntimeModule, new TheoryIdeModule))
	}
	
}
