/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xtheory
<<<<<<< HEAD:ac.soton.xtheory/src/ac/soton/xtheory/TheoryRuntimeModule.xtend

=======
>>>>>>> 963616839c6bebea4628b287134ece27bf40cfa7:ac.soton.xtheory/src/ac/soton/xtheory/TheoryRuntimeModule.xtend

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TheoryRuntimeModule extends AbstractTheoryRuntimeModule {
}